### PR TITLE
Moves things up to latest and greatest.

### PR DESCRIPTION
**Pull request by henrikengstrom**

### CODE REVIEW

**Comment by pvlugter** [comment]
I think the new dashboards should be under a `2.2.x` directory, not `2.1.x`?

**Comment by henrikengstrom** [comment]
Should I not add any changes to the 2.1.x and only move the 4.x series under 2.2.x as well?

**Comment by pvlugter** [comment]
Yes, all new stuff under 2.2.x, no changes to 2.1.x.

**Comment by henrikengstrom** [comment]
LGTM ;)

**Pull request merged**
